version: "3.9"

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: iprayio.api
    command: python api/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
    # depends_on:
    #   db:
    #     condition: service_healthy
    restart: unless-stopped
  
  # db:
  #   image: mysql:8.1
  #   container_name: iprayio.mysql
  #   environment:
  #     MYSQL_DATABASE: ipray.io
  #     MYSQL_USER: api
  #     MYSQL_ROOT_PASSWORD: Password1!
  #   ports:
  #     - 3307:3306
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   healthcheck:
  #       test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  #       timeout: 5s
  #       retries: 1
  #   restart: unless-stopped
  
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: iprayio.ui
    ports:
      - 80:3000
    restart: unless-stopped

volumes:
  mysql_data:
