version: "3.9"

services:
  worker:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: iprayio.worker
    command: python api/manage.py work
    volumes:
      - .:/app
    ports:
      - 8080:8080
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      DEBUG: ${DEBUG}
      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN}
      MAILGUN_FROM: ${MAILGUN_FROM}
      ADMIN_NOTIFICATION_EMAIL: ${ADMIN_NOTIFICATION_EMAIL}
    restart: unless-stopped
    depends_on:
      - api
  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: iprayio.api
    command: gunicorn --chdir api --worker-tmp-dir /dev/shm -c api/iprayio/gunicorn/conf.py config.wsgi:application
    volumes:
      - .:/app
    ports:
      - 80:80
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      DEBUG: ${DEBUG}
      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN}
      MAILGUN_FROM: ${MAILGUN_FROM}
      ADMIN_NOTIFICATION_EMAIL: ${ADMIN_NOTIFICATION_EMAIL}
    restart: unless-stopped

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: iprayio.ui
    ports:
      - 80:3000
    restart: unless-stopped

volumes:
  mysql_data:
